//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProyectoRespaldo.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Bitacora
    {
        public long id_respaldo { get; set; }
        public long id_maquina { get; set; }
        public Nullable<System.DateTime> hora_inicio { get; set; }
        public Nullable<System.DateTime> hora_fin { get; set; }
        public Nullable<int> fecha_respaldo { get; set; }
        public string nombre_archivo { get; set; }
        public Nullable<int> ruta_almacenamiento { get; set; }
        public byte[] estado { get; set; }
    
        public virtual maquina_virtual maquina_virtual { get; set; }
    }
}
