//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProyectoRespaldo.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Comando
    {
        public long Id_comando { get; set; }
        public string Nombre { get; set; }
        public string Opciones { get; set; }
        public string uso { get; set; }
    }
}
