//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProyectoRespaldo.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class maquina_virtual
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public maquina_virtual()
        {
            this.Bitacora = new HashSet<Bitacora>();
            this.politica = new HashSet<politica>();
        }
    
        public long Id_maquina { get; set; }
        public int id_servidor { get; set; }
        public string nombre { get; set; }
        public string estatus { get; set; }
        public string direccion_ip { get; set; }
        public Nullable<int> prioridad { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Bitacora> Bitacora { get; set; }
        public virtual servidor servidor { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<politica> politica { get; set; }
    }
}
