//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProyectoRespaldo.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class politica
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public politica()
        {
            this.maquina_virtual = new HashSet<maquina_virtual>();
        }
    
        public long id_politica { get; set; }
        public string nombre { get; set; }
        public Nullable<System.DateTime> fecha_fin { get; set; }
        public Nullable<System.TimeSpan> hora_inicio { get; set; }
        public Nullable<System.TimeSpan> hora_fin { get; set; }
        public string ruta_almacenamiento { get; set; }
        public Nullable<int> frecuencia_sem { get; set; }
        public Nullable<int> num_respaldos { get; set; }
        public string dias { get; set; }
        public string politica_default { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<maquina_virtual> maquina_virtual { get; set; }
    }
}
